### ISSUE TITLE
video dataset

### ISSUE THREAD

**Issue by Johnzu-2019** [v-iashin/BMT#11]
Hello!I would like to ask if you could share the video data set of this project with me. I would be very grateful if you could.My email address is 1075424318@qq.com.Thank you very much!

**Comment by v-iashin** [comment]
Hi,

Thanks for creating an issue. 

I would suggest you do something better. Check out this [ActivityNet Google Group](https://groups.google.com/g/activity-net) and search for topics where people are complaining that the dataset is not full anymore. The organizers share a google form that you can fill to get access to the FULL dataset. To replicate our results just filter it for files in `./data/available_mp4.txt`. 

Let me know if you will still need the exact videos which we used.

**Comment by Johnzu-2019** [comment]
yes, I&nbsp;need the exact videos which you used.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "v-iashin/BMT"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月4日(星期三) 下午4:34
收件人:&nbsp;"v-iashin/BMT"<BMT@noreply.github.com&gt;;
抄送:&nbsp;"读者"<1075424318@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [v-iashin/BMT] video dataset (#11)





 
Hi,
 
Thanks for creating an issue.
 
I would suggest you do something better. Check out this ActivityNet Google Group and search for topics where people are complaining that the dataset is not full anymore. The organizers share a google form that you can fill to get access to the FULL dataset. To replicate our results just filter it for files in ./data/available_mp4.txt.
 
Let me know if you will still need the exact videos which we used.

**Comment by Johnzu-2019** [comment]
> 你好
> 
> 感谢您创建问题。
> 
> 我建议你做得更好。查看这个[ActivityNet Google网上论坛，](https://groups.google.com/g/activity-net)并在人们抱怨数据集不完整的主题中搜索主题。组织者共享一个Google表单，您可以填写该表单以访问FULL数据集。要复制我们的结果，只需对中的文件进行过滤即可`./data/available_mp4.txt`。
> 
> 让我知道您是否仍然需要我们使用的确切视频。

Yes, I need the exact videos which you used.

**Comment by v-iashin** [comment]
Can I ask you why?

**Comment by Johnzu-2019** [comment]
> Can I ask you why?

Because I am a beginner. I have only the ability to fully reproduce your results.
