### ISSUE TITLE
503 service unavailable: cannot open a3s.fi links

### ISSUE THREAD

**Issue by v-iashin** [v-iashin/BMT#12]
Hi, 

Since this Monday the bucket storage that we use for storing features and models (`a3s`) is down. Usually, it takes several hours to recover but this time it is more serious, it seems. The problem is claimed to be 'temporally' but we are not sure when it will recover so for now please use this issue to let us know if you need any of the files ASAP – we will share them via other means.

Sorry for the trouble and good luck with your research!

**Comment by v-iashin** [comment]
Links to models:
[best_cap_model.pt](https://tuni-my.sharepoint.com/:u:/g/personal/vladimir_iashin_tuni_fi/ER8u-eLK1bZDi821JO3JRzMBRrmfRpQFXHSBnJAM1TtWpA?e=XZBoef) (`md5 hash 7b4d48cd77ec49a027a4a1abc6867ee7`).
[best_prop_model.pt](https://tuni-my.sharepoint.com/:u:/g/personal/vladimir_iashin_tuni_fi/EZK-9LfXcOJHsfa0G8ldqFEBEcdJyaLxluVztPvUTE1o6A?e=cJzZnL) (`md5 hash 5f8b20826b09eadd41b7a5be662c198b`).

The links will expire on the 17th of May, 2021. Therefore, avoid relying on them too much and, by default, use the links from the `README.md`.

**Comment by v-iashin** [comment]
The problem is resolved. Feel free to use this issue if you will have any trouble with the links.

**Comment by v-iashin** [comment]
The storage is down again

**Comment by YangBowenn** [comment]
> The storage is down again

The links of features and embeddings are also down, could you please upload them to another storage platform? Thank you!

**Comment by v-iashin** [comment]
Hi. Sorry for the trouble. There you go

[vggish_npy.zip](https://tuni-my.sharepoint.com/:u:/g/personal/vladimir_iashin_tuni_fi/EYbW2NGxPPdEjLx66pQasuwBqAs3_oCZTKpcOCK9bwUlWw?e=E5GIW0) `9a654ad785e801aceb70af2a5e1cffbe`
[i3d_25fps_stack64step64_2stream_npy](https://tuni-my.sharepoint.com/:u:/g/personal/vladimir_iashin_tuni_fi/EQXmAFMGyedLiEs-_MZsxy4BBnA7XnQnWlygUNtXvET6YQ?e=xMEYRH) `d7266e440f8c616acbc0d8aaa4a336dc`
[glove.840B.300d](https://tuni-my.sharepoint.com/:u:/g/personal/vladimir_iashin_tuni_fi/EQZc2c4zkWdHkLhl7hbUAZsBuJavlrEMEK1y6_f2-9BkTw?e=Whenrd) `2ffafcc9f9ae46fc8c95f32372976137`

Note, the links will work only until May 2021. Please rely on the downloading script in the repo unless it is not working.

**Comment by v-iashin** [comment]
Well, actually, the storage has recovered this morning. Are you sure that you cannot use the script?

**Comment by YangBowenn** [comment]
Oh, thanks a lot, the links has recovered just now.
