### ISSUE TITLE
BERT word embeddings

### ISSUE THREAD

**Issue by MorganeAyle** [v-iashin/BMT#13]
Hello,
Thank you for this great project!
Have you tried any word embedding model other than GloVe pre-trained embeddings, for example BERT pre-trained model?
Did you encouter any issues when trying such a model, or is there a reason you didn't use one?

**Comment by v-iashin** [comment]
Hi,
No, we haven't tried any other pre-trained embedding (the paper is not about it after all 🙂 ). 
Yes, I think it makes perfect sense and I would expect some improvements.
