### ISSUE TITLE
Why does the time of generating multiple captionings overlap?

### ISSUE THREAD

**Issue by wjy3326** [v-iashin/BMT#15]
Here is my result to use single_video_prediction.py to generate multiple captionings from raw video. First one sets the max_prop_per_vid equals to 20, the second result sets the max_prop_per_vid to 100.
result 1:
[{'start': 2.7, 'end': 37.9, 'sentence': 'A man is sitting on a chair talking to the camera'}, {'start': 1.6, 'end': 15.1, 'sentence': 'A man is sitting on a chair talking to the camera'}, {'start': 0.0, 'end': 127.7, 'sentence': 'A man is seen speaking to the camera while holding a microphone and leads into him speaking'}]
result 2:
[{'start': 2.7, 'end': 37.9, 'sentence': 'A man is sitting on a chair talking to the camera'}, {'start': 1.6, 'end': 15.1, 'sentence': 'A man is sitting on a chair talking to the camera'}, {'start': 0.0, 'end': 127.7, 'sentence': 'A man is seen speaking to the camera while holding a microphone and leads into him speaking'}, {'start': 0.3, 'end': 5.2, 'sentence': 'A man is seen sitting on a chair with a woman in a microphone'}, {'start': 109.0, 'end': 200.9, 'sentence': 'The man is talking to the camera'}, {'start': 283.4, 'end': 300.7, 'sentence': 'A man is seen speaking to the camera while holding a microphone'}]

Why does the time of multiple proposals overlap?  How can I get a non-overlapping event description? Thanks!

**Comment by v-iashin** [comment]
Because the task is called dense video captioning which implies that events may occur 'densely'.

See Fig 5 page 22 in our paper.

**Comment by v-iashin** [comment]
> How can I get a non-overlapping event description

Play with `--nms_tiou_thresh` argument in single video prediction.

**Comment by wjy3326** [comment]
Thanks! 
In the previous result above, I set  nms_tiou_thresh to 0.4. If I want to get a non-overlapping event description, how to set the parameter? 

I have another question here. When I set the parameter max_prop_per_vid equals to 20, I only get 3 sentences. When I set the parameter max_prop_per_vid to 100, I get 6 sentences, which much smaller than the max_prop_per_vid. Is the number of proposals or sentences related to nms_tiou_thresh or max_prop_per_vid? Which accounted for a greater proportion? Thanks!

**Comment by v-iashin** [comment]
As it follows from the name, `max_prop_per_vid` controls the maximum number of proposals per video – it will select the top-`max_prop_per_vid` out of all generated proposals sorted by its confidence.
https://github.com/v-iashin/BMT/blob/193faaae087293fa220c2a2422d1e8fdcfd6c037/sample/single_video_prediction.py#L189

Then the `nms_tiou_thresh` will be used to filter the top-`max_prop_per_vid` proposals. 
https://github.com/v-iashin/BMT/blob/193faaae087293fa220c2a2422d1e8fdcfd6c037/utilities/proposal_utils.py#L190

Imagine you have top-5 proposals with tious: [0.9, 0.8, 0.7, 0.8, 0.3]
if you set `nms_tiou_thresh` to be 0.85 all except the first will be used; if `nms_tiou_thresh=0.35` only the last one will be used.

If you like, you can reorganize the code a bit such that NMS (the thresholding) will be applied first and then you select the max number of proposals.
