### ISSUE TITLE
the score of result

### ISSUE THREAD

**Issue by NanjiaHan** [v-iashin/BMT#17]
When I use "best_cap_model.pt" and "prop_results_val_1_e17_maxprop100.json" which are provide in your code to generate captions, I find that the meteor score which is measured by the offical script  is 7.6. And I want to know how to get the result reported in the paper which can be more than 8.

**Comment by v-iashin** [comment]
It is hard to guess what is going on based on the info you are provided. Paste the code you used to obtain this.

Are you comparing using a reference file with all videos present? Try to follow the instructions in the README and read the paper more carefully.

**Comment by NanjiaHan** [comment]
Thanks for your response. I find my problem that I use a reference file with all videos of original dataset to compare.
