### ISSUE TITLE
create environment

### ISSUE THREAD

**Issue by shivani-2001** [v-iashin/BMT#19]
when i am creating environment i am facing this issue. please help me.
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - libgfortran-ng==7.3.0=hdf63c60_0
  - zlib==1.2.11=h7b6447c_3
  - cymem==1.31.2=py37h6bb024c_0
  - mkl_fft==1.0.15=py37ha843d7b_0
  - cryptography==2.8=py37h1ba5d50_0
  - libstdcxx-ng==9.1.0=hdf63c60_0
  - pytorch==1.2.0=py3.7_cuda10.0.130_cudnn7.6.2_0
  - tk==8.6.8=hbc83047_0
  - libgcc-ng==9.1.0=hdf63c60_0
  - ncurses==6.2=he6710b0_1
  - cytoolz==0.9.0.1=py37h14c3975_1
  - ninja==1.9.0=py37hfd86e86_0
  - regex==2018.07.11=py37h14c3975_0
  - thinc==6.10.3=py37h962f231_0
  - scikit-learn==0.22.1=py37hd81dba3_0
  - numpy-base==1.15.4=py37hde5b4d6_0
  - readline==8.0=h7b6447c_0
  - preshed==1.0.1=py37he6710b0_0
  - xz==5.2.5=h7b6447c_0
  - libffi==3.2.1=hd88cf55_4
  - mkl_random==1.1.0=py37hd6b4f25_0
  - numpy==1.15.4=py37h7e9f1db_0
  - openssl==1.1.1g=h7b6447c_0
  - murmurhash==0.28.0=py37hf484d3e_0
  - mkl-service==2.3.0=py37he904b0f_0
  - libedit==3.1.20181209=hc058e9b_0
  - python==3.7.7=hcf32534_0_cpython
  - sqlite==3.31.1=h62c20be_1
  - msgpack-python==0.5.6=py37h6bb024c_1
  - ld_impl_linux-64==2.33.1=h53a641e_7
  - protobuf==3.11.4=py37h3340039_1
  - pandas==0.24.2=py37he6710b0_0
  - scipy==1.3.1=py37h7c811a0_0
  - spacy==2.0.12=py37h962f231_0
  - ujson==2.0.3=py37he6710b0_0
  - cffi==1.14.0=py37h2e261b9_0
  - libprotobuf==3.11.4=h8b12597_0
  - openjdk==8.0.152=h7b6447c_3
  - wrapt==1.10.11=py37h14c3975_2

**Comment by v-iashin** [comment]
which system are you using?

**Comment by shivani-2001** [comment]
windows

**Comment by v-iashin** [comment]
It is not supported, sorry. But it doesn't mean the model will not work on Windows. It just means that you need to install the environment manually and fix the problems on your own, I am afraid. The package versions are there, so it should be easy. Feel free to share the differences between Linux and windows when it comes to setting up the environment for BMT. 

Also, check out this issue: https://github.com/v-iashin/MDVC/issues/17
