### ISSUE TITLE
The ratio of objectness loss coefficients to  the noobjectness coefficient

### ISSUE THREAD

**Issue by NanjiaHan** [v-iashin/BMT#20]
In the experiment, I find there are more negative samples. But the noobjectness coefficient is 100，it is more than objectness loss coefficients. So it's not clear why do you choose giving more weight to negative samples?

**Comment by v-iashin** [comment]
It is the other way around. It means that if the model fails to predict that there is no proposal, it will be penalized 100 times more than if it missed the proposal. See how YOLO is usually implemented.

Feel free to experiment with different coefficients and report them here. 

In our experiments, we found 100/1 to perform the best on the validation sets.
