### ISSUE TITLE
i3d features are corrupted while extracting via download.sh

### ISSUE THREAD

**Issue by amitesh-gaian** [v-iashin/BMT#3]
Hi,
I am trying to run the single_prediction.py for a different video with pretrained BMT model. It requires i3d features as well. The features that are uploaded are giving the corrupted error. Could you provide an alternate link for downloading the features?

Thanks for uploading the model and congrats on the publication.

**Comment by v-iashin** [comment]
Hi,

Thanks for reporting. This is strange. I tried it on several machines and it returns me the same md5 sum.

However, this error will also be given if your shell cannot find `md5sum` command. For instance, on a mac this is `md5`. Check out your terminal for more errors before the error that they are corrupted. Are you trying it on Linux? Could you also please share the md5 sum you are getting for your file?

Secondly, why do we need ActivityNet i3d features if we are trying to have predictions for a custom video?

Thirdly, if you would like to obtain predictions for ActivityNet Captions dataset you may find them in `./results/` folder.

**Comment by amitesh-gaian** [comment]
Hi,
Sorry for the wrong context and incomplete information. I tried single_prediction.py as well as main.py. The i3d file was corrupted and would not unzip. I downloaded i3d features manually from the link in the download.sh file and extracted it to the proper location and it worked.

**Comment by v-iashin** [comment]
Ok. Thanks. I am glad you found your way.

---

**If anyone comes across this issue and faces the same problem, please let me know here and I will change the procedure.**

**Comment by shivani-2001** [comment]
Same issue i am facing.

**Comment by v-iashin** [comment]
Thanks for letting me know.
Could you download the features manually?

**Comment by shivani-2001** [comment]
yes, I downloaded

**Comment by v-iashin** [comment]
Can you elaborate on how did you find out that they are corrupted?

**Comment by shivani-2001** [comment]
Downloading i3d features
./download_data.sh: line 3: wget: command not found
Downloading vggish features
./download_data.sh: line 5: wget: command not found
Downloading GloVe embeddings
mkdir: cannot create directory ‘.vector_cache’: File exists
./download_data.sh: line 11: wget: command not found
Checking for correctness of the downloaded files
md5sum: ./data/i3d_25fps_stack64step64_2stream_npy.zip: No such file or directory
ERROR: .zip file with i3d features is corrupted

**Comment by v-iashin** [comment]
`wget: command not found` didn't ring a bell?

**Comment by shivani-2001** [comment]
yes, that's why downloaded manually.
