### ISSUE TITLE
Where is Audio dataset in this repo?

### ISSUE THREAD

**Issue by yunsujeon** [v-iashin/BMT#30]
Hi, thanks to share your great codes!

i inference my own videos, and success (use pre-trained models)
but i didn't know what a dataset are..

**1. I found dataset, can you check it is correct?**
video : kinetics (deepmind)
audio : audioset (google research)

**2. In this repo/data, I think there is no audio dataset.**
train,test csv,json file is for video dataset (youtube video crawling)
and they have duration, timestemps, sentences
but i can't find audio dataset..
what are they?

thank you

**Comment by v-iashin** [comment]
Hi,
Thanks for reaching out and I am glad you liked it.

1. No, it is not.
We rely on pre-trained models (VGGish and I3D) to extract features for our system. The dataset which we extract these features for is ActivityNet Captions.

2. We operate on videos which have both visual and audio tracks.
Thus, a set of videos forms both.

**Comment by yunsujeon** [comment]
I think ActivityNet captions is video dataset.
And, I checked annotations in that video dataset.
So ,I want to know what form of speech annotation exists.
thx!

**Comment by v-iashin** [comment]
I think you confuse video captioning with closed captioning.

**Comment by yunsujeon** [comment]
Okay, I'll find out more about that, thank you very much.
