### ISSUE TITLE
Append some captions on Dataset and training

### ISSUE THREAD

**Issue by yunsujeon** [v-iashin/BMT#32]
Hello,

Thank you for responding to all issues. I have one question.

I inferenced my own video, but sentences accuracy is not so good.

So, I want to append more captions in dataset -> and training

---

You told me in my last question issue, BMT's dataset is Activitynet captions.

BMT/data/train.json is that.

and there also exist train.csv and etc..

**So I try to append captions in train.json and train.csv**

like this
![add_caption](https://user-images.githubusercontent.com/38097792/123754806-3e143c00-d8f6-11eb-9b12-d85b311bd990.png)

---

**but it doesn't work**
"""
Contructing caption_iterator for "train" phase
Traceback (most recent call last):
  File "main.py", line 186, in <module>
    main(cfg)
  File "main.py", line 11, in main
    train_cap(cfg)
  File "/home/piai/share/BMT/scripts/train_captioning_module.py", line 30, in train_cap
    train_dataset = ActivityNetCaptionsDataset(cfg, 'train', get_full_feat=False)
  File "/home/piai/share/BMT/datasets/captioning_dataset.py", line 310, in __init__
    self.train_vocab, self.caption_loader = caption_iterator(cfg, self.batch_size, self.phase)
  File "/home/piai/share/BMT/datasets/captioning_dataset.py", line 40, in caption_iterator
    CAPTION.build_vocab(dataset.caption, min_freq=cfg.min_freq_caps, vectors=cfg.word_emb_caps)
  File "/home/piai/anaconda3/envs/bmt/lib/python3.7/site-packages/torchtext/data/field.py", line 262, in build_vocab
    for x in data:
  File "/home/piai/anaconda3/envs/bmt/lib/python3.7/site-packages/torchtext/data/dataset.py", line 154, in __getattr__
    yield getattr(x, attr)
AttributeError: 'Example' object has no attribute 'caption'
"""

---

**And I found something wrong in train.csv and available_mp4.txt**
   
![traincsv](https://user-images.githubusercontent.com/38097792/123755154-977c6b00-d8f6-11eb-9fb9-831e1386e204.png)
**in this picture, there exist captions in start time column**
   
![availablemp4](https://user-images.githubusercontent.com/38097792/123755274-b1b64900-d8f6-11eb-94be-7951fbeb875d.png)
**in available_mp4, mp4's address is v_dZ~~ but in correct address i found is v=dZ~~**
   
So, Could you tell me how to append my own data?
   
Thankyou

**Comment by v-iashin** [comment]
Hi,

> in this picture, there exist captions in start time column
The problem is with the way how you display your csv file. Note, the format is called "*comma*-separated values" and captions tend to have commas in them. I use tabs for separation (`\t`). Therefore, just fix it on your side. There is nothing wrong with them.

> in available_mp4, mp4's address is v_dZ~~ but in correct address i found is v=dZ~~
It is good that you noticed but, again, you can just "Find-and-replace", right? There is no information loss due to this.
