### ISSUE TITLE
Can BMT generate the caption for the customized video?

### ISSUE THREAD

**Issue by WujiangXu** [v-iashin/BMT#39]
Hello, I want to use your fancy model to generate the caption for the customized video. But I am new for this task, is there a solution to generate the caption easily.

Thank you for your work!

**Comment by v-iashin** [comment]
Hello.

Yes, you can: 
1. https://colab.research.google.com/github/v-iashin/BMT/blob/master/colab_demo_BMT.ipynb
2. https://github.com/v-iashin/BMT#single-video-prediction
