### ISSUE TITLE
OSError: libtorch_cpu.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Rubatoo** [v-iashin/BMT#4]
Hi
when i tried to that, i got this error 

conda activate i3d
python main.py \
    --feature_type i3d \
    --on_extraction save_numpy \
    --device_ids 0 \
    --extraction_fps 25 \
    --video_paths ../../sample/women_long_jump.mp4 \
    --output_path ../../sample/

OSError: libtorch_cpu.so: cannot open shared object file: No such file or directory

how do i fix it?

**Comment by v-iashin** [comment]
Hi,

Thanks for reporting. 

Could you please share the conda environment you are trying to use to extract features?

**Comment by Rubatoo** [comment]
i just follow the 'Extract I3D features', so i used conda i3d

# packages in environment at /home/bg/anaconda3/envs/i3d:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    conda-forge
absl-py                   0.9.0                    pypi_0    pypi
autopep8                  1.4.4                      py_0    conda-forge
blas                      1.0                         mkl    conda-forge
brotlipy                  0.7.0           py37h7b6447c_1000  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2020.6.24                     0  
cachetools                4.1.1                    pypi_0    pypi
certifi                   2020.6.20                py37_0  
cffi                      1.14.0           py37he30daa8_1  
chardet                   3.0.4                 py37_1003  
cryptography              2.9.2            py37h1ba5d50_0  
cudatoolkit               10.0.130                      0  
cudnn                     7.3.1                cuda10.0_0  
cupy                      5.1.0            py37hc0ce245_0  
cymem                     1.31.2           py37h6bb024c_0  
cytoolz                   0.9.0.1          py37h14c3975_1  
dill                      0.2.9                    py37_0  
fastrlock                 0.4              py37he6710b0_0  
ffmpeg                    4.1.3                h167e202_0    conda-forge
flake8                    3.8.2                      py_0  
freetype                  2.9.1                h8a8886c_1  
future                    0.18.2                   py37_1  
gmp                       6.1.2                h6c8ec71_1  
gnutls                    3.6.5             h71b1129_1002  
google-auth               1.20.1                   pypi_0    pypi
google-auth-oauthlib      0.4.1                    pypi_0    pypi
grpcio                    1.31.0                   pypi_0    pypi
h5py                      2.8.0            py37h989c5e5_3  
hdf5                      1.10.2               hba1933b_1  
idna                      2.10                       py_0  
importlib-metadata        1.6.0                    py37_0  
intel-openmp              2020.1                      217  
jpeg                      9b                   h024ee3a_2  
lame                      3.100                h7b6447c_0  
ld_impl_linux-64          2.33.1               h53a641e_7    conda-forge
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.3                  he6710b0_1  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libiconv                  1.15                 h63c8f33_5  
libpng                    1.6.37               hbc83047_0  
libprotobuf               3.12.4               hd408876_0    anaconda
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_0  
markdown                  3.2.2                    pypi_0    pypi
mccabe                    0.6.1                    py37_1  
mkl                       2020.1                      217  
mkl-service               2.3.0            py37he904b0f_0  
mkl_fft                   1.0.15           py37ha843d7b_0  
mkl_random                1.1.1            py37h0573a6f_0  
msgpack-numpy             0.4.4.3                    py_0  
msgpack-python            0.5.6            py37h6bb024c_1  
murmurhash                0.28.0           py37hf484d3e_0  
nccl                      1.3.5                cuda10.0_0  
ncurses                   6.2                  he6710b0_1  
nettle                    3.4.1                hbb512f6_0  
ninja                     1.9.0            py37hfd86e86_0  
numpy                     1.15.4           py37h7e9f1db_0  
numpy-base                1.15.4           py37hde5b4d6_0  
oauthlib                  3.1.0                    pypi_0    pypi
olefile                   0.46                     py37_0  
opencv-python             4.1.0.25                 pypi_0    pypi
openh264                  1.8.0                hd408876_0  
openssl                   1.1.1g               h7b6447c_0  
pandas                    1.1.0            py37he6710b0_0  
pillow                    6.1.0            py37h34e0f95_0  
pip                       20.0.2                   py37_3  
plac                      0.9.6                    py37_1  
preshed                   1.0.1            py37he6710b0_0  
protobuf                  3.12.4           py37he6710b0_0    anaconda
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycodestyle               2.6.0                      py_0  
pycparser                 2.20                       py_0    conda-forge
pyflakes                  2.2.0                      py_0  
pyopenssl                 19.1.0                     py_1  
pysocks                   1.7.1                    py37_1  
python                    3.7.7                hcff3b4d_5  
python-dateutil           2.8.1                      py_0  
pytorch                   1.2.0           py3.7_cuda10.0.130_cudnn7.6.2_0    pytorch
pytz                      2020.1                     py_0  
readline                  8.0                  h7b6447c_0  
regex                     2018.07.11       py37h14c3975_0  
requests                  2.24.0                     py_0  
requests-oauthlib         1.3.0                    pypi_0    pypi
rope                      0.17.0                     py_0  
rsa                       4.6                      pypi_0    pypi
sentencepiece             0.1.91                   pypi_0    pypi
setuptools                46.4.0                   py37_0  
six                       1.14.0                   py37_0    conda-forge
spacy                     2.0.12           py37h962f231_0  
sqlite                    3.31.1               h62c20be_1  
tb-nightly                2.4.0a20200816           pypi_0    pypi
tensorboard-plugin-wit    1.7.0                    pypi_0    pypi
termcolor                 1.1.0                    py37_1  
thinc                     6.10.3           py37h962f231_0  
tk                        8.6.8                hbc83047_0  
toolz                     0.10.0                     py_0  
torchtext                 0.7.0                    pypi_0    pypi
tqdm                      4.46.0                     py_0  
ujson                     3.0.0            py37he6710b0_0  
urllib3                   1.25.10                    py_0  
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.34.2                   py37_0    conda-forge
wrapt                     1.10.11          py37h14c3975_2  
x264                      1!152.20180806       h7b6447c_0  
xz                        5.2.5                h7b6447c_0  
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0  


this is i3d conda list that i used

**Comment by v-iashin** [comment]
Ok are you trying to use cpu instead of a GPU?

**Comment by Rubatoo** [comment]
i want to use GPU

**Comment by v-iashin** [comment]
Ok. The list you shared has almost twice more lines than the original `conda_env.yml`. Please try to install reinstall the environment without any extra packages. Are you observing the same behavior?

**Comment by Rubatoo** [comment]
yes i tried to reinstall i3d envs. And i got this error.....

python main.py \
    --feature_type i3d \
    --on_extraction save_numpy \
    --device_ids 0 \
    --extraction_fps 25 \
    --video_paths ../../sample/women_long_jump.mp4 \
    --output_path ../../sample/

ImportError: TensorBoard logging requires TensorBoard with Python summary writer installed. This should be available in 1.14 or above.

**Comment by v-iashin** [comment]
Why do you need Tensorboard to extract features?

For your local problem, you can try to install `Tensorflow>=1.14`

**Comment by v-iashin** [comment]
> yes i tried to reinstall i3d envs. And i got this error.....
> 
> python main.py
> --feature_type i3d
> --on_extraction save_numpy
> --device_ids 0
> --extraction_fps 25
> --video_paths ../../sample/women_long_jump.mp4
> --output_path ../../sample/
> 
> ImportError: TensorBoard logging requires TensorBoard with Python summary writer installed. This should be available in 1.14 or above.

Faced the same error when forgot to `cd ./submodules/video_features` before running the script.
