### ISSUE TITLE
ERROR: .zip file with i3d features is corrupted

### ISSUE THREAD

**Issue by ppandgyy** [v-iashin/BMT#42]
Thank you for your excellent work
**Describe the bug**
when I bash ./download_data.sh

Checking for correctness of the downloaded files
md5sum: ./data/i3d_25fps_stack64step64_2stream_npy.zip: No such file or directory
ERROR: .zip file with i3d features is corrupted

**Looking forward to your reply**

**Comment by v-iashin** [comment]
Hi, there was some problem with our data storage provider during the last few days. It should be resolved by now.

Please try to download them again.

It seems like these are missing on your machine. If running the downloading script does not work try to do it explicitly:
`wget https://a3s.fi/swift/v1/AUTH_a235c0f452d648828f745589cde1219a/bmt/i3d_25fps_stack64step64_2stream_npy.zip -q --show-progress`
