### ISSUE TITLE
Error(s) in loading state_dict for DataParallel

### ISSUE THREAD

**Issue by tranhuynhkyanh** [v-iashin/BMT#44]
**Describe the bug**
I get this error when run Single video prediction

**Screenshots**
![image](https://user-images.githubusercontent.com/56480941/192225875-23404780-778f-4545-bf37-ac29c90f56a7.png)

How should I fix it ? Thanks

**Comment by v-iashin** [comment]
Can you share a small snippet of the code that you are using? Starting with `git clone repo-http-like` and up to the `python sindle_video_prediction.py`

The error tells me that the word dictionary might have different sizes of the ckpt and the model.

**Comment by tranhuynhkyanh** [comment]
I set up following your "Getting Started"  and  run the inference
![image](https://user-images.githubusercontent.com/56480941/192229651-13a56923-5fdf-42c6-8614-02b8818b5998.png)

**Comment by tranhuynhkyanh** [comment]
Thank you so much, i try it successful after follow your steps again. I think mistake is my spacy package when load model.
