### ISSUE TITLE
Error while extracting i3d features

### ISSUE THREAD

**Issue by shahchhatru** [v-iashin/BMT#46]
I wrote the following code in my terminal
`
conda env create -f conda_env_i3d.yml
conda activate i3d
python main.py \
    --feature_type i3d \
    --on_extraction save_numpy \
    --device_ids 0 \
    --extraction_fps 25 \
    --video_paths ../../test/pandemic.mp4 \
    --output_path ../../test/
`
![nocuda](https://user-images.githubusercontent.com/55979766/221716055-c4090fa6-1335-4495-aa74-3f88fde27618.png)

I believe this error is caused since I don't have Nvidia GPU . If my assumption for error is right , is there a way to use CPU for feature extraction please help me out

**Comment by v-iashin** [comment]
Extraction on cpu is not supported by this version of video_features. You can try to use the latest version of it (https://iashin.ai/video_features/). However I cannot guarantee reproduction.
