### ISSUE TITLE
About evaluation

### ISSUE THREAD

**Issue by AIENG2020** [v-iashin/BMT#50]
Hi Vladimir Iashin
Thanks for sharing such an awesome work!
Thanks for your quick reply!
I have some questions about evaluation:
1- How to increase the speed of evaluation process ?, I have RTX gpu and I got like 0411021941: learned_props 1by1 26 @ 0:   
    0%|          | 9/6998 [02:47<36:11:36, 18.64s/it].
2- Based on the paper "dataset is split into 50/25/25 % parts for training,validation, and testing" , but in the code there are only 
    train, val_1, and val_2, can explain this point please and what is the difference between validation & testing in your work?

**Comment by v-iashin** [comment]
Hi @AIENG2020 

Thanks for checking it out.

1. I am not sure. Try increasing the batch size.
2. 50% of videos is training set, 25% of videos are annotated twice and these represent the validation sets (two scores are averaged), and 25% are the testing videos that are not used in this work.
