### ISSUE TITLE
speech features

### ISSUE THREAD

**Issue by czprincefly** [v-iashin/BMT#6]
Hello, v-iashin. Thanks for your code! Can the speech features be added to this BMT project?

**Comment by v-iashin** [comment]
Hi. Thanks for your question. 

I have two answers to it

1. As a third modality. This would be wonderful but I haven't found a way yet. The main problem is Bi-modal attention which is applied only to two streams of information. So, I am not sure how seamless fusion could be done without giving one of the modalities the unfair advantage.
2. To replace audio or visual modalities with speech. Yes, it is possible. If you have some speech to text engine, you will only need to embed words and treat them in a similar way as other modalities are treated.

**Comment by czprincefly** [comment]
Thank you very much for your nice answer. Could you share the video data set of this project with me? My email address is  1017799644@qq.com

**Comment by v-iashin** [comment]
I am sorry, I cannot share the videos. 

Recently, I discovered this group https://groups.google.com/g/activity-net. Try to find posts there where people are complaining about missing data on YouTube. They have a form to fill to get 100% of the dataset and use `./data/available_mp4.txt` to filter it out to replicate our results.

**Comment by johnrachwan123** [comment]
Hello, as a follow question I would ask if in your opinion replacing any of the current two modalities with speech is worth trying and could lead to a better model. I saw your ablation study in your other Multi-Modal paper didn't show the effect of speech except when it was added with the two others.

**Comment by v-iashin** [comment]
I think this question is about MDVC (https://github.com/v-iashin/MDVC). We are not using speech for BMT.

**Comment by v-iashin** [comment]
Hi. I don't know as I haven't tried to incorporate speech modality in BMT. I think it is worth trying to replace both modalities with speech and see if it gives you an improvement.
