### ISSUE TITLE
missing ground truth files  (./tmp/extracted_targets_for_{phase}.pkl ).

### ISSUE THREAD

**Issue by minmax100** [v-iashin/BMT#9]
Hi v-iashin,

Nice work!

I got error message when tried to train proposal model, and the error seems come from missing ground truth file

    FileNotFoundError: [Errno 2] No such file or directory: './tmp/extracted_targets_for_val_1.pkl'

Could I know where I can download the related files? (e.g., ./tmp/extracted_targets_for_{phase}.pkl ).

Thanks!

**Comment by v-iashin** [comment]
Hi @minmax100 

Please share the full error message.

In the meantime, these files are generated when the training is done for the first time here: 
https://github.com/v-iashin/BMT/blob/3d0ed089da476787a7a0b84aab207a8e036a419e/datasets/proposal_dataset.py#L133

Does this part fails somehow or why they aren't generated in your case?

**Comment by minmax100** [comment]
Thanks for the hints. After checking the code, I found that it is due to an old Panda version (so that extract_targets actually failed). After upgrading the Panda version, the problem is solved.

Thanks again!

Below is the previous full error message.
-------------------------------
  File "BMT/datasets/proposal_dataset.py", line 145, in extract_targets
    dataset_targets = pickle.load(open(self.extracted_targets_path, 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: './tmp/extracted_targets_for_train.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 184, in <module>
    main(cfg)
  File "main.py", line 13, in main
    train_prop(cfg)
  File "BMT/scripts/train_proposal_generator.py", line 37, in train_prop
    train_dataset = ProposalGenerationDataset(cfg, 'train', train_dataset.pad_idx)
  File "BMT/datasets/proposal_dataset.py", line 53, in __init__
    self.dataset_targets = self.extract_targets()
  File "BMT/datasets/proposal_dataset.py", line 154, in extract_targets
    start_end_numpy = video_id_meta[['start', 'end']].to_numpy()
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py", line 4376, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'to_numpy'
